#! /bin/sh
echo "creating resulting files..."
#chmod 777 touchFile 
# this file is used to generating Result files of HSI test
for i in $(seq 5);
do name1=$(printf newKSC%02dNResult.mat $i);
	touch "$name1";
	chmod 777 "$name1";
done

for j in $(seq 5);
do name2=$(printf newKSC%02dN4Result.mat $j);
	touch "$name2";
	chmod 777 "$name2";
done

for k in $(seq 5);
do name3=$(printf newKSC%02dN8Result.mat $k);
	touch "$name3";
	chmod 777 "$name3";
done
